### ISSUE TITLE
`extract_ir/convert_compile_command_to_objectfile` does not support `arguments`-style compilation databases

### ISSUE THREAD

**Issue by 25pwn** [google/ml-compiler-opt#297]
`extract_ir` errors on certain compilation databases. 

In this case, I generated a compilation database for redis(uses Makefile) using [bear](https://github.com/rizsotto/Bear):
```
PYTHONPATH=:/home/user/ml-opt/ml-compiler-opt python3 /home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir.py --cmd_filter=^-O2|-Os|-Oz$ --input=/home/user/ml-opt/redis_repo/compile_commands.json --input_type=json --llvm_objcopy_path=build/bin/llvm-objcopy --output_dir=/home/user/ml-opt/redis_corpus
Traceback (most recent call last):
  File "/home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir.py", line 142, in <module>
    app.run(main)
  File "/home/user/ml-opt/mlgo_venv/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/user/ml-opt/mlgo_venv/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir.py", line 107, in main
    objs = extract_ir_lib.load_from_compile_commands(
  File "/home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir_lib.py", line 229, in load_from_compile_commands
    objs = [
  File "/home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir_lib.py", line 230, in <listcomp>
    convert_compile_command_to_objectfile(cmd, output_dir)
  File "/home/user/ml-opt/ml-compiler-opt/compiler_opt/tools/extract_ir_lib.py", line 210, in convert_compile_command_to_objectfile
    cmd = command['command']
KeyError: 'command'
```
This is occurs because `compiler_opt/tools/extract_ir_lib.py/convert_compile_command_to_objectfile` simply checks if `command` exists, when `arguments` may be present instead(see [JSON Compilation Database Format Specification/Format](https://clang.llvm.org/docs/JSONCompilationDatabase.html#format)).

This looks very easy to resolve: if `command` is missing but `arguments` is present, convert `arguments` to `command` by concatenation.

Do you mind if I fix this and create a pull request?

**Comment by boomanaiden154** [comment]
A PR would be great! Thanks for identifying this gap. It doesn't seem like there's any official standard for the JSON compilation database schema, but matching the behavior of clangd (or whatever other components read compilation databases) sounds good to me.

Also note that it's possible to extract a corpus from an app without using a compilation database (although it's currently not documented very well). If you set the input_type to directory, it will just run a glob over the directory passed to input for object files, which might be easier in your case rather than having to go through another tool like bear. It should come up with documentation if you run the script with --help.
